apache-rat-core/pom.xml
apache-rat-core/src/main/java/org/apache/rat/analysis/license/ApacheSoftwareLicense20.java
apache-rat-core/src/test/java/org/apache/rat/ReportTest.java
apache-rat-core/src/test/java/org/apache/rat/report/xml/XmlReportFactoryTest.java
apache-rat-core/src/test/java/org/apache/rat/report/xml/XmlReportTest.java
apache-rat-core/src/test/resources/elements/TextHttps.txt

An https url is currently classified as invalid.
According to https://issues.apache.org/jira/browse/LEGAL-265 these should be valid too.
This pull request intends to fix this.

RAT-212,RAT-253: Support all valid ASF2.0-License urls 

---

.travis.yml

Hello
Travis has problems with depencies incompatibilities. The simplest solution is to use Docker, which provides isolation of dependencies. 
https://issues.apache.org/jira/projects/RAT/issues/RAT-260
Best regards,

RAT-260: Use Docker in Travis CI to avoid animal-sniffer errors when building with various JDKs

---

README.md

Hello,
Current link is very confusing for users. We should link to travis status page.
Best regards,
Kamil

RAT-260: Fix link to Travis status page

---

apache-rat-plugin/src/main/java/org/apache/rat/mp/RatCheckMojo.java
src/changes/changes.xml

As requested by users and discussed via ML.

RAT-270: Change default logging behaviour to output errors onto console instead of rat.txt only

---

pom.xml

Needs to be merged once 0.14 is propagated as a new release
* vote thread is open until 2022-06-03 12:00 UTC
PR does not build properly as GH does not support defining custom repositories and the release 0.14 is not yet propagated to Maven central.

Use new release in build of 0.15-SNAPSHOT

---

apache-rat-core/src/main/java/org/apache/rat/Defaults.java
apache-rat-core/src/main/java/org/apache/rat/analysis/license/SPDXMatcher.java
apache-rat-core/src/test/java/org/apache/rat/analysis/license/SPDXMatcherTest.java

#148 significantly slowed processing in cases with files that have no recognized licences.  This change significantly speeds up the SPDX processing without sacrificing or changing the functionality.

RAT-251: Resolve slow down issues from pull request #148

---

apache-rat-core/pom.xml
apache-rat-core/src/main/java/org/apache/rat/Report.java
apache-rat-core/src/main/java/org/apache/rat/ReportConfiguration.java
apache-rat-core/src/main/java/org/apache/rat/walker/DirectoryWalker.java
apache-rat-core/src/main/java/org/apache/rat/walker/NameBasedHiddenFileFilter.java
apache-rat-core/src/main/java/org/apache/rat/walker/Walker.java
apache-rat-core/src/test/java/org/apache/rat/ReportConfigurationTest.java
apache-rat-core/src/test/java/org/apache/rat/ReportTest.java
apache-rat-core/src/test/java/org/apache/rat/ReporterTest.java
apache-rat-core/src/test/java/org/apache/rat/report/xml/XmlReportFactoryTest.java
apache-rat-core/src/test/java/org/apache/rat/report/xml/XmlReportTest.java
apache-rat-core/src/test/java/org/apache/rat/walker/DirectoryWalkerTest.java
apache-rat-plugin/pom.xml
apache-rat-plugin/src/main/java/org/apache/rat/mp/RatCheckMojo.java
apache-rat-tasks/pom.xml
apache-rat/README-CLI.txt
apache-rat/src/site/apt/index.apt.vm
pom.xml
src/changes/changes.xml

This is an alternative to #160

RAT-322: be able to scan hidden directories

---

apache-rat-plugin/pom.xml
apache-rat-plugin/src/main/java/org/apache/rat/mp/AbstractRatMojo.java
apache-rat-plugin/src/main/java/org/apache/rat/mp/util/ExclusionHelper.java
apache-rat-plugin/src/main/java/org/apache/rat/mp/util/ScmIgnoreParser.java
apache-rat-plugin/src/main/java/org/apache/rat/mp/util/ignore/GitIgnoreMatcher.java
apache-rat-plugin/src/main/java/org/apache/rat/mp/util/ignore/GlobIgnoreMatcher.java
apache-rat-plugin/src/main/java/org/apache/rat/mp/util/ignore/IgnoreMatcher.java
apache-rat-plugin/src/main/java/org/apache/rat/mp/util/ignore/IgnoringDirectoryScanner.java
apache-rat-plugin/src/test/java/org/apache/rat/mp/RatCheckMojoTest.java
apache-rat-plugin/src/test/java/org/apache/rat/mp/util/ExclusionHelperTest.java
apache-rat-plugin/src/test/java/org/apache/rat/mp/util/ScmIgnoreParserTest.java
apache-rat-plugin/src/test/resources/unit/RAT-335-GitIgnore/.gitignore
apache-rat-plugin/src/test/resources/unit/RAT-335-GitIgnore/README.txt
apache-rat-plugin/src/test/resources/unit/RAT-335-GitIgnore/dir1/.gitignore
apache-rat-plugin/src/test/resources/unit/RAT-335-GitIgnore/dir1/dir1.md
apache-rat-plugin/src/test/resources/unit/RAT-335-GitIgnore/dir1/dir1.txt
apache-rat-plugin/src/test/resources/unit/RAT-335-GitIgnore/dir1/file1.log
apache-rat-plugin/src/test/resources/unit/RAT-335-GitIgnore/dir2/dir2.md
apache-rat-plugin/src/test/resources/unit/RAT-335-GitIgnore/dir2/dir2.txt
apache-rat-plugin/src/test/resources/unit/RAT-335-GitIgnore/dir3/dir3.log
apache-rat-plugin/src/test/resources/unit/RAT-335-GitIgnore/dir3/file3.log
apache-rat-plugin/src/test/resources/unit/RAT-335-GitIgnore/invoker.properties
apache-rat-plugin/src/test/resources/unit/RAT-335-GitIgnore/pom.xml
apache-rat-plugin/src/test/resources/unit/RAT-335-GitIgnore/root.md
pom.xml

Fixing the issue described in https://issues.apache.org/jira/browse/RAT-335
Correctly following the rules in a gitignore file is not simply checking them all and stopping if one matches. So for the actual parsing and evaluation I have used a library I wrote a while ago for this exact purpose.
To allow having more complex rules like this and the default rules side by side I have added a `IgnoreMatcher` interface. A new subclass of `DirectoryScanner` is used which will check both the provided `IgnoreMatcher` instances and the existing rules.
Please let me know what you think of this approach.

RAT-335: Improve the parsing of gitignore files.

---

apache-rat-plugin/pom.xml

Just updating to the latest version.
This fixes some of the special expressions in a gitignore file that are allowed yet poorly documented.

RAT-348: Update gitignore reader

---

apache-rat-plugin/src/main/java/org/apache/rat/mp/AbstractRatMojo.java

The place where the NPE occurs is here 
https://github.com/apache/creadur-rat/blob/21b726a0945f905d67ef8854950aa1e4530873a3/apache-rat-core/src/main/java/org/apache/rat/Reporter.java#L56
Because no config is set the stylesheet is null which NPEs on the `.get()`.
If you normally set a config without a styleSheet something similar is done.

RAT-349: Fix NPE on addDefaultLicenses=false

---

apache-rat-plugin/pom.xml

As mentioned here https://github.com/apache/creadur-rat/pull/194#issuecomment-1890590107 if the integration tests fails the build does not fail.
The cause is that currently the build uses the `integration-test` goal which is documented as `will never fail the build`: https://maven.apache.org/plugins/maven-invoker-plugin/plugin-info.html
The `run` goal does the same thing and will let the build fail if one of the tests fails.

RAT-349: Fail the build if integration tests fail

---

apache-rat-core/src/main/java/org/apache/rat/Report.java
apache-rat-core/src/main/java/org/apache/rat/ReportConfiguration.java
apache-rat-core/src/main/java/org/apache/rat/analysis/DefaultAnalyserFactory.java
apache-rat-core/src/main/java/org/apache/rat/analysis/DocumentHeaderAnalyser.java
apache-rat-core/src/main/java/org/apache/rat/analysis/LicenseCollection.java
apache-rat-core/src/main/java/org/apache/rat/analysis/matchers/CopyrightMatcher.java
apache-rat-core/src/main/java/org/apache/rat/analysis/matchers/SPDXMatcherFactory.java
apache-rat-core/src/main/java/org/apache/rat/annotation/AbstractLicenseAppender.java
apache-rat-core/src/main/java/org/apache/rat/annotation/ApacheV2LicenseAppender.java
apache-rat-core/src/main/java/org/apache/rat/api/MetaData.java
apache-rat-core/src/main/java/org/apache/rat/report/claim/impl/xml/SimpleXmlClaimReporter.java
apache-rat-core/src/main/java/org/apache/rat/report/claim/util/LicenseAddingReport.java
apache-rat-core/src/main/java/org/apache/rat/report/xml/XmlReportFactory.java
apache-rat-core/src/main/java/org/apache/rat/utils/DefaultLog.java
apache-rat-core/src/main/java/org/apache/rat/utils/Log.java
apache-rat-core/src/test/java/org/apache/rat/ReportConfigurationTest.java
apache-rat-core/src/test/java/org/apache/rat/ReportTest.java
apache-rat-core/src/test/java/org/apache/rat/ReporterTest.java
apache-rat-core/src/test/java/org/apache/rat/analysis/AnalyserFactoryTest.java
apache-rat-core/src/test/java/org/apache/rat/analysis/matchers/SPDXMatcherTest.java
apache-rat-core/src/test/java/org/apache/rat/annotation/TestLicenseAppender.java
apache-rat-core/src/test/java/org/apache/rat/report/xml/XmlReportFactoryTest.java
apache-rat-core/src/test/java/org/apache/rat/report/xml/XmlReportTest.java

In my small test case this changed the timing from 55 sec to 3 sec.

RAT-325 : Added check to skip expensive processing in SPDX

---

apache-rat-core/src/main/java/org/apache/rat/Report.java
apache-rat-core/src/main/java/org/apache/rat/utils/DefaultLog.java

Rather than moving the file lists to the noisier DEBUG level I update the default logging level to WARN.  This seems appropriate for CLI.
The default logging level only applies to the CLI and  tests.
In all other extant UIs the logging is performed by the native system and so the logging needs to be set there.

RAT-325: Changed CLI-default logging level to WARN

---

.buildtools/generateStagingSiteInWebpageRepo
apache-rat-plugin/pom.xml
pom.xml

Filed a bug in the maven-plugin-report-plugin: [MPLUGIN-507](https://issues.apache.org/jira/browse/MPLUGIN-507)
[RAT-353](https://issues.apache.org/jira/browse/RAT-353) brought to the light that the following files were not generated in RAT 0.16 and 0.16.1:
* plugin-info.html
* check-mojo.html
* rat-mojo.html
due to a breaking change in maven-plugin-annotations v3.11.0 that separated the generation logics into a new plugin a new configuration is needed. This new plugin yields a NPE and breaks the site build.

RAT-353, MPLUGIN-507: Enable maven-plugin-report-plugin to see NPE with Maven 4.x only

---

apache-rat-core/pom.xml
pom.xml

This fixes https://issues.apache.org/jira/browse/RAT-367 and now also the older tests are run on each build.

RAT-367: Enable running old junit tests during the build with junit5

---

apache-rat-plugin/pom.xml
apache-rat-plugin/src/main/java/org/apache/rat/mp/util/ignore/GitIgnoreMatcher.java
apache-rat-plugin/src/test/java/org/apache/rat/mp/RatCheckMojoTest.java
apache-rat-plugin/src/test/resources/unit/RAT-362-GitIgnore/.gitignore
apache-rat-plugin/src/test/resources/unit/RAT-362-GitIgnore/foo.md
apache-rat-plugin/src/test/resources/unit/RAT-362-GitIgnore/invoker.properties
apache-rat-plugin/src/test/resources/unit/RAT-362-GitIgnore/pom.xml

This fixes https://issues.apache.org/jira/browse/RAT-362

RAT-362, RAT-345: Fix gitignore directory handling - switch to relative paths in underlying library

---

apache-rat-core/pom.xml
apache-rat-core/src/main/java/org/apache/rat/Report.java
apache-rat-core/src/main/resources/org/apache/rat/missing-headers.xsl
apache-rat-core/src/test/java/org/apache/rat/ReportTransformerTest.java
apache-rat-core/src/test/resources/XmlOutputExamples/elements.xml
apache-rat-plugin/pom.xml
apache-rat/src/site/apt/index.apt.vm
src/changes/changes.xml
src/site/apt/index.apt.vm

Fix for RAT-77
This was mostly fixed earlier.  This pull 
- adds another stylesheet to the package (missing-headers.xsl) to the two that already existed: plain-rat (default), missing-headers, and unapproved-licenses
- allows the -s option to use a short name (e.g. `-s missing-headers` or `-s unapproved-licenses`
- updates the documentation to talk about the stylesheets.

RAT-77: output files with missing headers

---

apache-rat-tasks/src/main/java/org/apache/rat/anttasks/Report.java

This fixes an issue detected in the build output where the tail end of the output disappears, though the build appears to work correctly.
The issue is that the ant report test manages to close System.out.  This change ensures that System.out does not get closed.

RAT-355, RAT-366: Fixed closed output issue

---

pom.xml
src/changes/changes.xml

@Claudenw I was unable to read the docs properly - there is a solution that I`ve added that lets the build fail if new errors are added. At the moment there are 63 open issues within RAT.
Feel free to hit the merge button if that is fine with you.

RAT-369: Let the build fail in case of new violations/spotbugs errors

---

apache-rat-core/src/main/java/org/apache/rat/Report.java
apache-rat-core/src/main/java/org/apache/rat/report/claim/impl/xml/SimpleXmlClaimReporter.java
apache-rat-core/src/main/java/org/apache/rat/report/claim/util/ClaimReporterMultiplexer.java
apache-rat-core/src/main/java/org/apache/rat/report/xml/XmlReportFactory.java
apache-rat-core/src/test/java/org/apache/rat/ReportTest.java
apache-rat-core/src/test/java/org/apache/rat/configuration/XMLConfigurationWriterTest.java
apache-rat-core/src/test/resources/report/LicenseOne.xml
apache-rat-core/src/test/resources/report/LicenseTwo.xml

This code is dependant upon #246 and should not be merged until that one is merged.
This is not a fix for Rat-190 as that issue was solved with the Tika introduction.  
This change fixes some issues with the current source code.
- --list-licenses not working.
- null command line argument erroring out strangly
- multiple typos
- error mixing standard XML and configuration XML reports in one run.

RAT-190: Fixes for minor bugs that blocked problem detection

---

apache-rat-core/src/main/java/org/apache/rat/Defaults.java
apache-rat-core/src/main/java/org/apache/rat/Report.java
apache-rat-core/src/main/java/org/apache/rat/ReportConfiguration.java
apache-rat-core/src/main/java/org/apache/rat/analysis/DefaultAnalyserFactory.java
apache-rat-core/src/main/java/org/apache/rat/analysis/UnknownLicense.java
apache-rat-core/src/main/java/org/apache/rat/analysis/matchers/SPDXMatcherFactory.java
apache-rat-core/src/main/java/org/apache/rat/api/MetaData.java
apache-rat-core/src/main/java/org/apache/rat/configuration/MatcherBuilderTracker.java
apache-rat-core/src/main/java/org/apache/rat/configuration/builders/ChildContainerBuilder.java
apache-rat-core/src/main/java/org/apache/rat/license/ILicense.java
apache-rat-core/src/main/java/org/apache/rat/license/LicenseSetFactory.java
apache-rat-core/src/main/java/org/apache/rat/license/SimpleLicense.java
apache-rat-core/src/test/java/org/apache/rat/ReportConfigurationTest.java
apache-rat-core/src/test/java/org/apache/rat/ReportTest.java
apache-rat-core/src/test/java/org/apache/rat/analysis/DefaultAnalyserFactoryTest.java
apache-rat-core/src/test/java/org/apache/rat/analysis/HeaderCheckWorkerTest.java
apache-rat-core/src/test/java/org/apache/rat/analysis/license/AbstractLicenseTest.java
apache-rat-core/src/test/java/org/apache/rat/analysis/matchers/SPDXMatcherTest.java
apache-rat-core/src/test/java/org/apache/rat/configuration/XMLConfigurationReaderTest.java
apache-rat-core/src/test/java/org/apache/rat/license/SimpleLicenseTest.java
apache-rat-core/src/test/java/org/apache/rat/policy/DefaultPolicyTest.java
apache-rat-core/src/test/java/org/apache/rat/report/xml/XmlReportFactoryTest.java
apache-rat-core/src/test/java/org/apache/rat/testhelpers/TestingLicense.java
apache-rat-plugin/src/test/java/org/apache/rat/mp/RatCheckMojoTest.java
apache-rat/src/site/apt/index.apt.vm
src/changes/changes.xml

Fixes RAT-377
This change is dependent upon RAT-372 and should not be considered for merged until after that change has been accepted.
The solution for process archive files (RAT-372) introduces a command line switch to change from just reporting the presence of archive files to reporting what licenses they contain or reporting licenses contains as well as missing licenses.
This request is for a similar change in STANDARD reporting.
The use case is for non-ASF projects that don't require a license header in every file but do require licensing to be declared within the project.
Using `--standard PRESENCE`  would cause Rat to list all the declared licenses in the scan, without the overhead noise of 'missing license headers'

RAT-377: Create a STANDARD process filter like the  ARCHIVE process switch in RAT-372

---

.github/workflows/maven.yml
.mvn/develocity.xml
.mvn/extensions.xml

@ottlinger, it was nice meeting you at Community over Code today. This PR will enable you to publish Build Scans to [ge.apache.org](https://ge.apache.org/) as discussed.
This PR publishes a build scan for every CI build and for every local build from an authenticated Apache committer. The build will not fail if publishing fails. Local and remote caching was left disabled on this PR by design so that the build is not affected by this change. 
The build scans of the Apache Creadur RAT project are published to the Develocity instance at [ge.apache.org](https://ge.apache.org/), hosted by the Apache Software Foundation and run in partnership between the ASF and Gradle. This Develocity instance has all features and extensions enabled and is freely available for use by the Apache Creadur RAT …

Develocity integration

---

apache-rat-core/src/main/java/org/apache/rat/report/xml/writer/IXmlWriter.java
apache-rat-core/src/main/java/org/apache/rat/report/xml/writer/OperationNotAllowedException.java
apache-rat-core/src/main/java/org/apache/rat/report/xml/writer/impl/base/XmlWriter.java
apache-rat-core/src/main/java/org/apache/rat/report/xml/writer/package-info.java
src/conf/checkstyle-suppressions.xml

fix for RAT-430
Ignored magic numbers nad javadoc in old XmlWriter code
Leaves an issue with `report/xml/writer/impl/base` not having a `package-info.java` file, but I think that we should probably move all the files into `report/xml/writer` after RAT-323 is completed

RAT-430: fixed checkstyle issues in report/xml

---

apache-rat-core/src/main/java/org/apache/rat/analysis/HeaderCheckWorker.java
apache-rat-core/src/main/java/org/apache/rat/analysis/IHeaderMatcher.java
apache-rat-core/src/main/java/org/apache/rat/analysis/UnknownLicense.java
apache-rat-core/src/main/java/org/apache/rat/license/ILicense.java
apache-rat-core/src/main/java/org/apache/rat/license/ILicenseFamily.java
apache-rat-core/src/main/java/org/apache/rat/license/ILicenseFamilyBuilder.java
apache-rat-core/src/main/java/org/apache/rat/license/LicenseSetFactory.java
apache-rat-core/src/main/java/org/apache/rat/license/SimpleLicense.java
apache-rat-core/src/main/java/org/apache/rat/license/SimpleLicenseFamily.java
apache-rat-core/src/main/java/org/apache/rat/license/package-info.java
apache-rat-core/src/main/java/org/apache/rat/report/claim/ClaimStatistic.java
apache-rat-core/src/main/java/org/apache/rat/report/claim/impl/ClaimAggregator.java
apache-rat-core/src/main/java/org/apache/rat/report/claim/util/LicenseAddingReport.java
src/changes/changes.xml

Fixed for RAT-426
Also moved ILicenseFamilyBuilder into ILicenseFamily.Builder to simplify the code.

RAT-426: fixed checkstyle in licenses and moved ILicenseFamily builder

---

apache-rat-core/src/main/java/org/apache/rat/ReportConfiguration.java
apache-rat-core/src/main/java/org/apache/rat/commandline/Arg.java
apache-rat-core/src/main/java/org/apache/rat/document/DocumentNameMatcherSupplier.java
apache-rat-core/src/test/java/org/apache/rat/test/AbstractOptionsProvider.java
src/changes/changes.xml

Fix for RAT-2
Added --input-exclude-size <bytes> as an option to skip the scanning of very small files.

RAT-2: Added --input-exclude-size option

---

apache-rat-core/src/it/resources/ReportTest/RAT_455/commandLine.txt
apache-rat-core/src/it/resources/ReportTest/RAT_455/src/GPL.md
apache-rat-core/src/it/resources/ReportTest/RAT_455/verify.groovy
apache-rat-core/src/it/resources/ReportTest/RAT_457/commandLine.txt
apache-rat-core/src/main/resources/org/apache/rat/asf.xml
apache-rat-core/src/main/resources/org/apache/rat/default.xml
apache-rat-core/src/test/java/org/apache/rat/DefaultsTest.java
apache-rat-core/src/test/java/org/apache/rat/ReportConfigurationTest.java
apache-rat-core/src/test/java/org/apache/rat/analysis/license/GPLLicenseTest.java
apache-rat-core/src/test/java/org/apache/rat/configuration/FormatTest.java
apache-rat-core/src/test/java/org/apache/rat/configuration/XMLConfigurationReaderTest.java
apache-rat-core/src/test/java/org/apache/rat/policy/DefaultPolicyTest.java
apache-rat-core/src/test/java/org/apache/rat/report/ConfigurationReportTest.java
apache-rat-core/src/test/java/org/apache/rat/testhelpers/TextUtils.java
apache-rat-tools/pom.xml
src/changes/changes.xml

Fix for RAT-455
Removed GPL licenses from approved license family listing.
Updated tests
Added integration test.

RAT-455: no GPL licenses allowed in default config

---

apache-rat-core/src/main/build-grv/copyResourcesFromParentProject.groovy

As https://github.com/apache/creadur-rat/pull/408 did not work out and all changes are on master already let's start a discussion here.

RAT-397: Make project importable into Eclipse

---

apache-rat-core/src/main/java/org/apache/rat/OptionCollection.java
apache-rat-core/src/main/java/org/apache/rat/ReportConfiguration.java
apache-rat-core/src/main/java/org/apache/rat/api/Document.java
apache-rat-core/src/main/java/org/apache/rat/document/FileDocument.java
apache-rat-core/src/main/java/org/apache/rat/walker/ArchiveWalker.java
apache-rat-core/src/test/java/org/apache/rat/DefaultsTest.java
apache-rat-core/src/test/java/org/apache/rat/ReportConfigurationTest.java
apache-rat-core/src/test/java/org/apache/rat/ReporterTest.java
apache-rat-core/src/test/java/org/apache/rat/report/xml/XmlReportFactoryTest.java
apache-rat-core/src/test/java/org/apache/rat/test/AbstractOptionsProvider.java
apache-rat-core/src/test/java/org/apache/rat/walker/DirectoryWalkerTest.java
apache-rat-plugin/src/main/java/org/apache/rat/mp/AbstractRatMojo.java
apache-rat-tasks/src/main/java/org/apache/rat/anttasks/ResourceCollectionContainer.java

Changed name of variable(s) and method to be lexically correct.  It is not a document name matcher but rather an excluder.  
Part of #417 simplification.

RAT-98: changed 'name matcher' to 'document excluder'

---

apache-rat-core/pom.xml
apache-rat-core/src/it/java/org/apache/rat/ReportTest.java
apache-rat-core/src/main/java/org/apache/rat/api/Document.java
apache-rat-core/src/main/java/org/apache/rat/config/exclusion/ExclusionUtils.java
apache-rat-core/src/main/java/org/apache/rat/config/exclusion/plexus/MatchPattern.java
apache-rat-core/src/main/java/org/apache/rat/config/exclusion/plexus/MatchPatterns.java
apache-rat-core/src/main/java/org/apache/rat/document/ArchiveEntryName.java
apache-rat-core/src/main/java/org/apache/rat/document/DocumentName.java
apache-rat-core/src/main/java/org/apache/rat/document/DocumentNameMatcher.java
apache-rat-core/src/main/java/org/apache/rat/document/FileDocument.java
apache-rat-core/src/main/java/org/apache/rat/walker/ArchiveWalker.java
apache-rat-core/src/main/java/org/apache/rat/walker/FileListWalker.java
apache-rat-core/src/test/java/org/apache/rat/OptionCollectionTest.java
apache-rat-core/src/test/java/org/apache/rat/analysis/AnalyserFactoryTest.java
apache-rat-core/src/test/java/org/apache/rat/config/exclusion/ExclusionProcessorTest.java
apache-rat-core/src/test/java/org/apache/rat/config/exclusion/FileProcessorTest.java
apache-rat-core/src/test/java/org/apache/rat/document/DocumentNameTest.java
apache-rat-core/src/test/java/org/apache/rat/document/FSInfoTest.java
apache-rat-core/src/test/java/org/apache/rat/document/guesser/NoteGuesserTest.java
apache-rat-core/src/test/java/org/apache/rat/test/AbstractOptionsProvider.java
apache-rat-core/src/test/java/org/apache/rat/testhelpers/TestingDocument.java
apache-rat-core/src/test/java/org/apache/rat/walker/FileListWalkerTest.java
pom.xml

This a a part of #417 and is here to simplify the review.
The FSInfo allows us to easily test multiple file systems without having to create actual file systems.  It extracts away the file system info that we need for document name checks and add Google JimFS for testing.
Other changes include change DocumentName.baseName to a DocumentName rather than a string.  This adds some complexity to the builder but makes other checks much easier.

RAT-98: Added FSInfo to handle file system differences

---

apache-rat-core/src/main/java/org/apache/rat/document/DocumentNameMatcher.java

Quick fix to redo a missing idiom misuse correction.

RAT-98: fixed DocumentNameMatcher idiom misuse

---

apache-rat-core/src/test/java/org/apache/rat/analysis/AnalyserFactoryTest.java
apache-rat-core/src/test/java/org/apache/rat/config/exclusion/ExclusionProcessorTest.java
apache-rat-core/src/test/java/org/apache/rat/document/guesser/NoteGuesserTest.java
apache-rat-core/src/test/java/org/apache/rat/test/AbstractOptionsProvider.java

RAT-98: Changes to tests for multi OS and FileDocument change

---

apache-rat-core/src/main/java/org/apache/rat/document/DocumentNameMatcher.java

RAT-98: updated DocumentNameMatcher

---

apache-rat-core/src/main/java/org/apache/rat/config/exclusion/StandardCollection.java
apache-rat-core/src/main/java/org/apache/rat/config/exclusion/fileProcessors/AbstractFileProcessorBuilder.java
apache-rat-core/src/main/java/org/apache/rat/config/exclusion/fileProcessors/GitIgnoreBuilder.java
apache-rat-core/src/test/java/org/apache/rat/config/exclusion/fileProcessors/AbstractIgnoreBuilderTest.java
apache-rat-core/src/test/java/org/apache/rat/config/exclusion/fileProcessors/GitIgnoreBuilderTest.java
apache-rat-core/src/test/resources/GitIgnoreBuilderTest/global-gitignore
apache-rat-core/src/test/resources/GitIgnoreBuilderTest/src/.gitignore
apache-rat-core/src/test/resources/GitIgnoreBuilderTest/src/local-should-precede-global.md
apache-rat-core/src/test/resources/GitIgnoreBuilderTest/src/local-should-precede-global.xml
src/changes/changes.xml

Take into account exclusions from the global gitignore file if it is present in the default location. It's kind of icky to read environment variables in code called from an enum constructor, but I didn't see a more elegant solution yet either. Relatedly, I have not yet created a unit test (or made sure that a global gitignore will not interfere with a global gitignore being present), hence the WIP status.
https://git-scm.com/docs/gitignore

RAT-473: take global gitignore into account 

---

apache-rat-core/.gitignore
apache-rat-core/src/it/resources/ReportTest/RAT_406/commandLine.txt
apache-rat-core/src/it/resources/ReportTest/RAT_406/expected-message.txt
apache-rat-core/src/it/resources/ReportTest/RAT_406/src/dojo/dojo.java
apache-rat-core/src/main/java/org/apache/rat/OptionCollection.java
apache-rat-core/src/main/java/org/apache/rat/Reporter.java
apache-rat-core/src/test/java/org/apache/rat/OptionCollectionTest.java
apache-rat-core/src/test/java/org/apache/rat/ReporterOptionsTest.java
apache-rat-core/src/test/java/org/apache/rat/test/AbstractConfigurationOptionsProvider.java
apache-rat-core/src/test/java/org/apache/rat/test/AbstractOptionsProvider.java
apache-rat-core/src/test/java/org/apache/rat/test/utils/OptionFormatter.java
apache-rat-core/src/test/java/org/apache/rat/testhelpers/TextUtils.java
apache-rat-core/src/test/java/org/apache/rat/testhelpers/XmlUtils.java
apache-rat-plugin/src/test/java/org/apache/rat/mp/OptionMojoTest.java
apache-rat-plugin/src/test/java/org/apache/rat/mp/RatCheckMojoTest.java
apache-rat-tasks/src/test/java/org/apache/rat/anttasks/ReportOptionTest.java
src/changes/changes.xml

closes #406 
Additional tests to prove #406 is closed and to provide easy extension points for future tests of command line combinations.
- Added integration test for 406
- Extracted `AbstractConfigOptionsProvider` from `AbstractOptionsProvider`.
- Added `ReporterOptionsTest`  to test the result of passing arguments to the `Reporter`.  Tests all the options.
- `Reporter.output()` now returns a `ClaimStatistic` instance.

RAT-406: Tests to prove that issue is fixed

---

apache-rat-core/src/it/resources/ReportTest/RAT_335/src/.gitignore
apache-rat-core/src/it/resources/ReportTest/RAT_335/src/README.txt
apache-rat-core/src/it/resources/ReportTest/RAT_335/src/dir1/.gitignore
apache-rat-core/src/it/resources/ReportTest/RAT_335/verify.groovy
apache-rat-core/src/main/java/org/apache/rat/config/exclusion/fileProcessors/AbstractFileProcessorBuilder.java

* Adjusted RAT-355 test a per git reporting of include/exclude
Discovered RAT 335 was not 100% correct, then discovered that RAT-476 already covers the issue that I uncovered in RAT-335 test.  So rat 335 test is adjusted to show current state and has note to indicate why.
Also added comment to RAT-476 indicating that RAT-335 test should be updated when it is fixed.

Added information about RAT-476 to RAT-335 test

---

apache-rat-tasks/src/test/java/org/apache/rat/anttasks/ReportOptionTest.java

In order to stabilize release builds apart from LinuxGHA we could disable the dangling test on WindowsJDK8 as well.
WDYT?

RAT-475: Disable test on GHA windows/JDK8
