- apache-rat-plugin/src/main/java/org/apache/rat/mp/util/ExclusionHelper.java
- apache-rat-plugin/src/test/java/org/apache/rat/mp/util/ExclusionHelperTest.java
> RAT-266: Add .factorypath to Eclipse default excludes

- apache-rat-plugin/src/main/java/org/apache/rat/mp/RatCheckMojo.java
- apache-rat-plugin/src/main/java/org/apache/rat/mp/RatReportMojo.java
- src/changes/changes.xml
AFAIK, the rat mojos seem to be thread-safe.
Nevertheless, If that change requires proper testing, I could write some tests (but I would need some guiding on how to do that).
> RAT-207: Properly report thread safety to Maven

- RELEASE_NOTES.txt
- pom.xml
- src/changes/changes.xml
As soon as 0.15 is properly approved and released this branch can be merged.
> Adapt for release 0.15

- apache-rat-plugin/src/main/java/org/apache/rat/mp/AbstractRatMojo.java
- apache-rat-plugin/src/main/java/org/apache/rat/mp/RatReportMojo.java
- apache-rat-plugin/src/main/java/org/apache/rat/mp/util/ScmIgnoreParser.java
Use DEBUG instead of INFO for some logging events
> RAT-317: Maven plugin is too chatty

- pom.xml
Added Claude Warren as a contributor
> RAT-251: Update pom.xml

- src/changes/changes.xml
Updated changes.xml for pull request #148
> RAT-251: Update changes.xml about ability for SPDX processing

- apache-rat-core/src/main/java/org/apache/rat/ReportConfiguration.java
- apache-rat-core/src/test/java/org/apache/rat/ReportConfigurationTest.java
Ensured the System.out does not get closed and updated javadocs. 
Added class to allow others to wrap similar streams in a no close format.
> RAT-328 Fix for IOSupplier issue includes javadoc updates

- .gitignore
- apache-rat-core/src/main/java/org/apache/rat/annotation/AbstractLicenseAppender.java
- apache-rat-core/src/test/java/org/apache/rat/annotation/TestLicenseAppender.java
Added md processing for inserting licenses.
> RAT-329 - Added md and yaml processing

- apache-rat-core/src/main/java/org/apache/rat/report/RatReport.java
- src/site/md/architecture.md
No jira for this change.  I added a simple overview of the architecture in the hopes that we will expand it and keep it up to date so that new developers will have some idea of how this works.
> added architecture.md and javadocs for RatReport

- apache-rat-plugin/pom.xml
- apache-rat-plugin/src/it/CustomLicense/invoker.properties
- apache-rat-plugin/src/it/CustomLicense/pom.xml
- apache-rat-plugin/src/it/CustomLicense/src/main/java/nl/basjes/something/Something.java
- apache-rat-plugin/src/main/java/org/apache/rat/mp/Family.java
- apache-rat-plugin/src/main/java/org/apache/rat/mp/License.java
A simple test to ensure custom licenses work
> RAT-343: Add test to validate allowing a custom license

- apache-rat-plugin/pom.xml
- src/changes/changes.xml
> RAT-348: Update GitIgnore reader to version 1.3.1

- apache-rat-plugin/src/site/apt/examples/custom-license.apt.vm
I am unsure of how to format this text, and I don't have a viewer that displays it.  Any assistance in editing/viewing would be appreciated, but I think the gist is here.
> RAT-343: add examples

- apache-rat-plugin/src/site/apt/examples/custom-license.apt.vm
Fix and enhance documentation about how to configure custom licenses.
> RAT-343: Enhance documentation about new configuration options

- apache-rat-core/src/main/java/org/apache/rat/ReportConfiguration.java
Added code to delete a File if it exists and is passed to the report configuration for output.
closes RAT-344
> RAT-344 ensured that if a File is provided for output is is deleted first

- apache-rat-core/src/main/java/org/apache/rat/annotation/AbstractLicenseAppender.java
- apache-rat-core/src/main/java/org/apache/rat/utils/Log.java
- apache-rat-core/src/test/java/org/apache/rat/annotation/TestLicenseAppender.java
- src/changes/changes.xml
Fix for RAT-333
Added test to cover the issue as well as a general test to show that the "force" command works.
> RAT-333: fix --force option will change the file permissions

- README.md
@ottlinger - I added the Develocity badge to `README.md`, as requested [here](https://github.com/apache/creadur-rat/pull/263#issuecomment-2148354591). Let me know if you'd like to change anything 👍
> Added Develocity badge to README.md

- .buildtools/generateStagingSiteInWebpageRepo
- .buildtools/generateStagingSiteInWebpageRepo-release
- .github/workflows/maven.yml
- apache-rat-tasks/pom.xml
- pom.xml
- src/changes/changes.xml
Fixes RAT-409
added flags targets to create a complete site build
> RAT-409: Site build requires Project target

- apache-rat-core/src/main/java/org/apache/rat/OptionCollection.java
- apache-rat-core/src/test/java/org/apache/rat/OptionCollectionTest.java
- apache-rat-core/src/test/java/org/apache/rat/help/HelpTest.java
- src/changes/changes.xml
The generated argument_types.txt from Help.java are shown to render multiple dots.
> RAT-441: Multiple dots are rendered

- apache-rat-core/src/main/java/org/apache/rat/analysis/matchers/AbstractHeaderMatcher.java
- apache-rat-core/src/main/java/org/apache/rat/analysis/matchers/AbstractMatcherContainer.java
- apache-rat-core/src/main/java/org/apache/rat/analysis/matchers/AndMatcher.java
- apache-rat-core/src/main/java/org/apache/rat/analysis/matchers/FullTextMatcher.java
- apache-rat-core/src/main/java/org/apache/rat/analysis/matchers/NotMatcher.java
- apache-rat-core/src/main/java/org/apache/rat/analysis/matchers/OrMatcher.java
- apache-rat-core/src/main/java/org/apache/rat/analysis/matchers/SPDXMatcherFactory.java
- apache-rat-core/src/main/java/org/apache/rat/analysis/matchers/SimpleRegexMatcher.java
- apache-rat-core/src/main/java/org/apache/rat/analysis/matchers/SimpleTextMatcher.java
- apache-rat-core/src/main/java/org/apache/rat/analysis/matchers/package-info.java
- src/changes/changes.xml
> RAT-411: fixed checkstyle issues in analysis/matchers

- apache-rat-core/src/main/java/org/apache/rat/annotation/AbstractLicenseAppender.java
- src/changes/changes.xml
> RAT-413: checkstyle fixes for annotation package

- apache-rat-core/src/main/java/org/apache/rat/config/parameters/ComponentType.java
- apache-rat-core/src/main/java/org/apache/rat/config/parameters/ConfigComponent.java
- apache-rat-core/src/main/java/org/apache/rat/config/parameters/Description.java
- apache-rat-core/src/main/java/org/apache/rat/config/parameters/DescriptionBuilder.java
- apache-rat-core/src/main/java/org/apache/rat/config/parameters/MatcherBuilder.java
- apache-rat-core/src/main/java/org/apache/rat/config/parameters/package-info.java
- src/changes/changes.xml
> RAT-419: Checkstyle fixes for config/parameters package

- apache-rat-core/src/main/java/org/apache/rat/document/RatDocumentAnalysisException.java
- apache-rat-core/src/main/java/org/apache/rat/document/package-info.java
- src/changes/changes.xml
> RAT-424: Fixed checkstyle issues in document package

- apache-rat-core/src/main/java/org/apache/rat/help/Licenses.java
- src/changes/changes.xml
> RAT-425:  Fixed help checkstyle issues

- src/conf/checkstyle-suppressions.xml
Removed deprecated code from consideration
> RAT-438: checkstyle fixes for apache-rat-tasks

- apache-rat-plugin/src/main/java/org/apache/rat/mp/All.java
- apache-rat-plugin/src/main/java/org/apache/rat/mp/Any.java
- apache-rat-plugin/src/main/java/org/apache/rat/mp/Copyright.java
- apache-rat-plugin/src/main/java/org/apache/rat/mp/EnclosingMatcher.java
- apache-rat-plugin/src/main/java/org/apache/rat/mp/Family.java
- apache-rat-plugin/src/main/java/org/apache/rat/mp/HeaderMatcherSpecification.java
- apache-rat-plugin/src/main/java/org/apache/rat/mp/License.java
- apache-rat-plugin/src/main/java/org/apache/rat/mp/Not.java
- apache-rat-plugin/src/main/java/org/apache/rat/mp/RatCheckException.java
- apache-rat-plugin/src/main/java/org/apache/rat/mp/RatCheckMojo.java
- apache-rat-plugin/src/main/java/org/apache/rat/mp/RatReportMojo.java
- apache-rat-plugin/src/main/java/org/apache/rat/mp/Regex.java
- apache-rat-plugin/src/main/java/org/apache/rat/mp/Spdx.java
- apache-rat-plugin/src/main/java/org/apache/rat/mp/Text.java
- apache-rat-plugin/src/main/java/org/apache/rat/mp/package-info.java
- src/changes/changes.xml
- src/conf/checkstyle-suppressions.xml
Fix for RAT-436
Fixed checkstyle issues
- Marked deprecated code
- Removed deprecated code from checkstyle consideration
- Fixed checkstyle issues.
- Fixed javadoc issue.
> RAT-436: checkstyle fixes for plugin

- apache-rat-plugin/pom.xml
- src/changes/changes.xml
@Claudenw feel free to merge directly if ok for you. Thanks.
> RAT-451: Generate plugin code into the same package

- apache-rat-core/src/it/java/org/apache/rat/ReportTest.java
- apache-rat-core/src/main/java/org/apache/rat/commandline/Arg.java
- apache-rat-core/src/main/java/org/apache/rat/utils/Log.java
- apache-rat-core/src/test/java/org/apache/rat/test/AbstractOptionsProvider.java
Added ability to set log level in all cases or lot that it is not supported
> Quick fix for log breaking build

- apache-rat-core/src/it/resources/ReportTest/RAT_458/commandLine.txt
- apache-rat-core/src/it/resources/ReportTest/RAT_458/src/README.md
- apache-rat-core/src/it/resources/ReportTest/RAT_458/verify.groovy
- src/changes/changes.xml
Closes Issue RAT-458.
Testing verifies that command line works.
> RAT-458: Added IT test for --log-level setting

- apache-rat-core/src/it/resources/ReportTest/RAT_457/commandLine.txt
- apache-rat-core/src/it/resources/ReportTest/RAT_457/verify.groovy
- src/changes/changes.xml
Fix for RAT-457, RAT-18 and RAT-456
Added test to verify that jar processing occurs correctly.
> RAT-457: Added test to very jar processing

- apache-rat-core/src/main/java/org/apache/rat/analysis/HeaderCheckWorker.java
- apache-rat-core/src/main/java/org/apache/rat/api/MetaData.java
- apache-rat-core/src/main/java/org/apache/rat/report/claim/SimpleXmlClaimReporter.java
- apache-rat-core/src/main/java/org/apache/rat/report/xml/XmlElements.java
- apache-rat-core/src/main/resources/org/apache/rat/plain-rat.xsl
- apache-rat-core/src/main/resources/org/apache/rat/rat-report.xsd
- apache-rat-core/src/test/java/org/apache/rat/ReporterTest.java
- apache-rat-core/src/test/java/org/apache/rat/analysis/DefaultAnalyserFactoryTest.java
- src/changes/changes.xml
Fix for RAT-405
removed SAMPLE collection and reporting
> RAT-405: Remove Sample from XML output

- apache-rat-core/src/main/java/org/apache/rat/analysis/DefaultAnalyserFactory.java
- apache-rat-core/src/test/java/org/apache/rat/analysis/DefaultAnalyserFactoryTest.java
- apache-rat-core/src/test/java/org/apache/rat/analysis/TikaProcessorTest.java
- src/changes/changes.xml
Added tests to TikaProcessorTests and DefaultAnalyserFactoryTest
> RAT-178: Test binary guesser errors

- apache-rat-core/src/it/resources/ReportTest/RAT_14/verify.groovy
- apache-rat-core/src/main/java/org/apache/rat/OptionCollection.java
- apache-rat-core/src/main/java/org/apache/rat/Report.java
- apache-rat-core/src/main/java/org/apache/rat/commandline/ArgumentContext.java
- apache-rat-core/src/main/java/org/apache/rat/config/exclusion/ExclusionProcessor.java
- apache-rat-core/src/main/java/org/apache/rat/config/exclusion/plexus/MatchPattern.java
- apache-rat-core/src/main/java/org/apache/rat/config/exclusion/plexus/MatchPatterns.java
- apache-rat-core/src/main/java/org/apache/rat/document/DocumentNameMatcher.java
- apache-rat-core/src/test/java/org/apache/rat/OptionCollectionTest.java
- apache-rat-core/src/test/java/org/apache/rat/ReporterTest.java
- apache-rat-core/src/test/java/org/apache/rat/commandline/ArgTests.java
- apache-rat-core/src/test/java/org/apache/rat/document/DocumentNameMatcherTest.java
- apache-rat-core/src/test/java/org/apache/rat/test/AbstractOptionsProvider.java
- apache-rat-core/src/test/java/org/apache/rat/test/utils/Resources.java
- apache-rat-core/src/test/java/org/apache/rat/testhelpers/XmlUtils.java
- apache-rat-plugin/src/main/java/org/apache/rat/mp/AbstractRatMojo.java
- apache-rat-plugin/src/test/java/org/apache/rat/mp/OptionMojoTest.java
- apache-rat-tasks/src/main/java/org/apache/rat/anttasks/Report.java
- apache-rat-tasks/src/test/java/org/apache/rat/anttasks/ReportOptionTest.java
- apache-rat-tools/src/main/java/org/apache/rat/tools/Documentation.java
Added working directory to resolve relative document names in preparation for resolving against file lists and exclude processors
> RAT-98: Add working directory to resolve relative document names

- apache-rat-core/src/test/java/org/apache/rat/OptionCollectionTest.java
- apache-rat-core/src/test/java/org/apache/rat/document/DocumentNameBuilderTest.java
Updated tests and added test for DocumentNameBuilder.
> RAT-98: updated tests

- apache-rat-core/src/main/java/org/apache/rat/configuration/XMLConfigurationReader.java
- apache-rat-core/src/main/java/org/apache/rat/report/xml/writer/XmlWriter.java
- apache-rat-core/src/main/java/org/apache/rat/utils/Log.java
Added/updated logging messages.
> RAT-98: Improve logging messages

- apache-rat-core/src/main/java/org/apache/rat/analysis/TikaProcessor.java
- apache-rat-core/src/main/java/org/apache/rat/config/exclusion/plexus/SelectorUtils.java
- apache-rat-core/src/main/java/org/apache/rat/document/ArchiveEntryDocument.java
- apache-rat-tasks/src/test/java/org/apache/rat/anttasks/ReportOptionTest.java
Several simple non-functional changes
> RAT-98: simple non-functional changes

- src/site/apt/index.apt.vm
> RAT-358: updated documentation for building RAT
